### ISSUE TITLE
please update jws from 0.0.2 to 2.0.0

### ISSUE THREAD

**Issue by CTAPbIuMABP** [bsphere/node-gapitoken#15]

**Comment by FredKSchott** [comment]
:+1: 3.0.0 has superceded 2.0.0

**Comment by josephpage** [comment]
Please please please !! :)
< jws 2.0.0 has critical vulnerabilities. 
https://github.com/brianloveswords/node-jws/blob/master/CHANGELOG.md

**Comment by bsphere** [comment]
Can you submit a PR?
