### ISSUE TITLE
Publish 0.1.5

### ISSUE THREAD

**Issue by myndzi** [bsphere/node-gapitoken#20]
0.1.4 is still the latest version on NPM, and it depends on JWS@0.0.2, which is out of date and deprecated for security reasons. Please pulbish 0.1.5 so that the dependency can be installed correctly :)

**Comment by frank-dspeed** [comment]
is merged npm publish so that i dont need to patch the googleapis package.json to "gapitoken": "git+https://github.com/bsphere/node-gapitoken.git"

**Comment by myndzi** [comment]
I'm not sure what you're saying, but if you are telling me to use the git repo instead of the package name, that's not an acceptable solution.

**Comment by frank-dspeed** [comment]
hehehe no i am telling you to run npm publish on this version because i now needed to fork the googleapis to implament that it uses this git repo directly because current version of this is not published on npm !

**Comment by jeduan** [comment]
+1 I'm getting the same deprecation notices and all it takes is to publish the latest version

**Comment by bsphere** [comment]
done
