### ISSUE TITLE
Depricated dependency - JWS

### ISSUE THREAD

**Issue by set-killer** [bsphere/node-gapitoken#22]
When I install the package `gitkitclient`, it have dependency for this package and I get the following warning:

```
npm WARN deprecated jws@0.0.2: Security update: Versions below 3.0.0 are deprecated.
npm WARN deprecated tap-consumer@0.0.1: This module is not supported. Please use 'tap' instead.
npm WARN installMany tap-consumer was bundled with tap@0.3.3, but bundled package wasn't found in unpacked tree
npm WARN deprecated tap-results@0.0.2: This module is not supported. Please use 'tap' instead.
```

Is it possible to migrate to a newer version of jws?

**Comment by bsphere** [comment]
`gapitoken` is already updated to use `jws` ~3.0.0, latest version is 0.1.5. The problem is the the `googleapis` which `gitkitclient` uses (version 1.0.0) has gapitoken 0.1.2 as dependency.

I suggest you'll open an issue for `gitkitclient` to update the version of `googleapis`, latest is 2.1.5

**Comment by set-killer** [comment]
Yep, thank you :)
